# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'fe15main.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QSpinBox, QStatusBar, QWidget)
import portraits_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(491, 610)
        palette = QPalette()
        brush = QBrush(QColor(30, 30, 30, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush)
        brush1 = QBrush(QColor(46, 23, 15, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        MainWindow.setPalette(palette)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frmConfig = QFrame(self.centralwidget)
        self.frmConfig.setObjectName(u"frmConfig")
        self.frmConfig.setGeometry(QRect(10, 10, 471, 251))
        palette1 = QPalette()
        gradient = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient.setSpread(QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0, QColor(94, 48, 48, 255))
        gradient.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush2 = QBrush(gradient)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush2)
        gradient1 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient1.setSpread(QGradient.Spread.PadSpread)
        gradient1.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient1.setColorAt(0, QColor(94, 48, 48, 255))
        gradient1.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush3 = QBrush(gradient1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush3)
        gradient2 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient2.setSpread(QGradient.Spread.PadSpread)
        gradient2.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient2.setColorAt(0, QColor(94, 48, 48, 255))
        gradient2.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush4 = QBrush(gradient2)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush4)
        gradient3 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient3.setSpread(QGradient.Spread.PadSpread)
        gradient3.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient3.setColorAt(0, QColor(94, 48, 48, 255))
        gradient3.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush5 = QBrush(gradient3)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush5)
        gradient4 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient4.setSpread(QGradient.Spread.PadSpread)
        gradient4.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient4.setColorAt(0, QColor(94, 48, 48, 255))
        gradient4.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush6 = QBrush(gradient4)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush6)
        gradient5 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient5.setSpread(QGradient.Spread.PadSpread)
        gradient5.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient5.setColorAt(0, QColor(94, 48, 48, 255))
        gradient5.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush7 = QBrush(gradient5)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush7)
        gradient6 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient6.setSpread(QGradient.Spread.PadSpread)
        gradient6.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient6.setColorAt(0, QColor(94, 48, 48, 255))
        gradient6.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush8 = QBrush(gradient6)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush8)
        gradient7 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient7.setSpread(QGradient.Spread.PadSpread)
        gradient7.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient7.setColorAt(0, QColor(94, 48, 48, 255))
        gradient7.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush9 = QBrush(gradient7)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush9)
        gradient8 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient8.setSpread(QGradient.Spread.PadSpread)
        gradient8.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient8.setColorAt(0, QColor(94, 48, 48, 255))
        gradient8.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush10 = QBrush(gradient8)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush10)
        self.frmConfig.setPalette(palette1)
        self.frmConfig.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.495, cy:0.153727, radius:1.53642, fx:0.495, fy:0.154, stop:0 rgba(94, 48, 48, 255), stop:0.789474 rgba(37, 22, 21, 255));")
        self.frmConfig.setFrameShape(QFrame.Shape.StyledPanel)
        self.frmConfig.setFrameShadow(QFrame.Shadow.Raised)
        self.lblPersonagem = QLabel(self.frmConfig)
        self.lblPersonagem.setObjectName(u"lblPersonagem")
        self.lblPersonagem.setGeometry(QRect(10, 50, 121, 31))
        palette2 = QPalette()
        brush11 = QBrush(QColor(190, 141, 142, 255))
        brush11.setStyle(Qt.BrushStyle.SolidPattern)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush11)
        brush12 = QBrush(QColor(58, 7, 21, 255))
        brush12.setStyle(Qt.BrushStyle.SolidPattern)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush11)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush11)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush12)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush12)
        brush13 = QBrush(QColor(0, 0, 0, 255))
        brush13.setStyle(Qt.BrushStyle.SolidPattern)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush13)
        brush14 = QBrush(QColor(255, 255, 255, 255))
        brush14.setStyle(Qt.BrushStyle.SolidPattern)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush14)
        brush15 = QBrush(QColor(190, 141, 142, 128))
        brush15.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush11)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush11)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush11)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush12)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush12)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush13)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush11)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush12)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush11)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush11)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush12)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush12)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush13)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        self.lblPersonagem.setPalette(palette2)
        font = QFont()
        font.setFamilies([u"Microsoft YaHei"])
        font.setPointSize(14)
        self.lblPersonagem.setFont(font)
        self.lblPersonagem.setAutoFillBackground(False)
        self.lblPersonagem.setStyleSheet(u"background-color: rgb(58, 7, 21);    /* Tom vinho escuro do fundo da caixinha */\n"
"    color: rgb(190, 141, 142);\n"
"    border: 1px solid #4a1a24;    /* Borda sutil levemente mais clara que o fundo */\n"
"    border-radius: 4px;           /* Arredondamento dos cantos */\n"
"    padding: 3px 6px;\n"
"	margin: 1px;")
        self.lblPersonagem.setFrameShape(QFrame.Shape.WinPanel)
        self.lblPersonagem.setScaledContents(False)
        self.lblPersonagem.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblPersonagem.setWordWrap(False)
        self.lblClasse = QLabel(self.frmConfig)
        self.lblClasse.setObjectName(u"lblClasse")
        self.lblClasse.setGeometry(QRect(60, 80, 71, 31))
        palette3 = QPalette()
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush11)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush11)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush11)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush12)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush12)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush13)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush11)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush11)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush11)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush12)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush12)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush13)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush11)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush12)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush11)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush11)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush12)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush12)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush13)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        self.lblClasse.setPalette(palette3)
        self.lblClasse.setFont(font)
        self.lblClasse.setAutoFillBackground(False)
        self.lblClasse.setStyleSheet(u"background-color: rgb(58, 7, 21);    /* Tom vinho escuro do fundo da caixinha */\n"
"    color: rgb(190, 141, 142);\n"
"    border: 1px solid #4a1a24;    /* Borda sutil levemente mais clara que o fundo */\n"
"    border-radius: 4px;           /* Arredondamento dos cantos */\n"
"    padding: 3px 6px;\n"
"	margin: 1px;")
        self.lblClasse.setFrameShape(QFrame.Shape.Box)
        self.lblClasse.setScaledContents(False)
        self.lblClasse.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblClasse.setWordWrap(False)
        self.lblNivel = QLabel(self.frmConfig)
        self.lblNivel.setObjectName(u"lblNivel")
        self.lblNivel.setGeometry(QRect(60, 110, 71, 31))
        palette4 = QPalette()
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush11)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush11)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush11)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush12)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush12)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush13)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush11)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush11)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush11)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush12)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush12)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush13)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush11)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush12)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush11)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush11)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush12)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush12)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush13)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        self.lblNivel.setPalette(palette4)
        self.lblNivel.setFont(font)
        self.lblNivel.setAutoFillBackground(False)
        self.lblNivel.setStyleSheet(u"background-color: rgb(58, 7, 21);    /* Tom vinho escuro do fundo da caixinha */\n"
"    color: rgb(190, 141, 142);\n"
"    border: 1px solid #4a1a24;    /* Borda sutil levemente mais clara que o fundo */\n"
"    border-radius: 4px;           /* Arredondamento dos cantos */\n"
"    padding: 3px 6px;\n"
"	margin: 1px;")
        self.lblNivel.setFrameShape(QFrame.Shape.StyledPanel)
        self.lblNivel.setScaledContents(False)
        self.lblNivel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblNivel.setWordWrap(False)
        self.cbbPersonagem = QComboBox(self.frmConfig)
        self.cbbPersonagem.setObjectName(u"cbbPersonagem")
        self.cbbPersonagem.setGeometry(QRect(140, 50, 201, 31))
        font1 = QFont()
        font1.setFamilies([u"Microsoft YaHei"])
        font1.setPointSize(12)
        self.cbbPersonagem.setFont(font1)
        self.cbbPersonagem.setStyleSheet(u"background-color: rgb(70, 20, 29);")
        self.cbbPersonagem.setLabelDrawingMode(QComboBox.LabelDrawingMode.UseDelegate)
        self.cbbClasse = QComboBox(self.frmConfig)
        self.cbbClasse.setObjectName(u"cbbClasse")
        self.cbbClasse.setGeometry(QRect(140, 80, 201, 31))
        self.cbbClasse.setFont(font1)
        self.cbbClasse.setStyleSheet(u"background-color: rgb(70, 20, 29);")
        self.cbbClasse.setLabelDrawingMode(QComboBox.LabelDrawingMode.UseDelegate)
        self.spbLevel = QSpinBox(self.frmConfig)
        self.spbLevel.setObjectName(u"spbLevel")
        self.spbLevel.setGeometry(QRect(140, 110, 201, 31))
        self.spbLevel.setFont(font1)
        self.spbLevel.setStyleSheet(u"background-color: rgb(69, 20, 29);")
        self.spbLevel.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.spbLevel.setMinimum(1)
        self.spbLevel.setMaximum(20)
        self.frmInfoTitulo = QFrame(self.frmConfig)
        self.frmInfoTitulo.setObjectName(u"frmInfoTitulo")
        self.frmInfoTitulo.setGeometry(QRect(0, 0, 521, 41))
        palette5 = QPalette()
        gradient9 = QLinearGradient(0, 0, 0.5, 0)
        gradient9.setSpread(QGradient.Spread.PadSpread)
        gradient9.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient9.setColorAt(0, QColor(148, 58, 77, 255))
        gradient9.setColorAt(1, QColor(116, 25, 38, 255))
        brush16 = QBrush(gradient9)
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush16)
        gradient10 = QLinearGradient(0, 0, 0.5, 0)
        gradient10.setSpread(QGradient.Spread.PadSpread)
        gradient10.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient10.setColorAt(0, QColor(148, 58, 77, 255))
        gradient10.setColorAt(1, QColor(116, 25, 38, 255))
        brush17 = QBrush(gradient10)
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush17)
        gradient11 = QLinearGradient(0, 0, 0.5, 0)
        gradient11.setSpread(QGradient.Spread.PadSpread)
        gradient11.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient11.setColorAt(0, QColor(148, 58, 77, 255))
        gradient11.setColorAt(1, QColor(116, 25, 38, 255))
        brush18 = QBrush(gradient11)
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush18)
        gradient12 = QLinearGradient(0, 0, 0.5, 0)
        gradient12.setSpread(QGradient.Spread.PadSpread)
        gradient12.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient12.setColorAt(0, QColor(148, 58, 77, 255))
        gradient12.setColorAt(1, QColor(116, 25, 38, 255))
        brush19 = QBrush(gradient12)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush19)
        gradient13 = QLinearGradient(0, 0, 0.5, 0)
        gradient13.setSpread(QGradient.Spread.PadSpread)
        gradient13.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient13.setColorAt(0, QColor(148, 58, 77, 255))
        gradient13.setColorAt(1, QColor(116, 25, 38, 255))
        brush20 = QBrush(gradient13)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush20)
        gradient14 = QLinearGradient(0, 0, 0.5, 0)
        gradient14.setSpread(QGradient.Spread.PadSpread)
        gradient14.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient14.setColorAt(0, QColor(148, 58, 77, 255))
        gradient14.setColorAt(1, QColor(116, 25, 38, 255))
        brush21 = QBrush(gradient14)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush21)
        gradient15 = QLinearGradient(0, 0, 0.5, 0)
        gradient15.setSpread(QGradient.Spread.PadSpread)
        gradient15.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient15.setColorAt(0, QColor(148, 58, 77, 255))
        gradient15.setColorAt(1, QColor(116, 25, 38, 255))
        brush22 = QBrush(gradient15)
        palette5.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush22)
        gradient16 = QLinearGradient(0, 0, 0.5, 0)
        gradient16.setSpread(QGradient.Spread.PadSpread)
        gradient16.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient16.setColorAt(0, QColor(148, 58, 77, 255))
        gradient16.setColorAt(1, QColor(116, 25, 38, 255))
        brush23 = QBrush(gradient16)
        palette5.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush23)
        gradient17 = QLinearGradient(0, 0, 0.5, 0)
        gradient17.setSpread(QGradient.Spread.PadSpread)
        gradient17.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient17.setColorAt(0, QColor(148, 58, 77, 255))
        gradient17.setColorAt(1, QColor(116, 25, 38, 255))
        brush24 = QBrush(gradient17)
        palette5.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush24)
        self.frmInfoTitulo.setPalette(palette5)
        self.frmInfoTitulo.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.5, y2:0, stop:0 rgb(148, 58, 77), stop:1 rgb(116, 25, 38));")
        self.frmInfoTitulo.setFrameShape(QFrame.Shape.StyledPanel)
        self.frmInfoTitulo.setFrameShadow(QFrame.Shadow.Plain)
        self.lblPersonagem_2 = QLabel(self.frmInfoTitulo)
        self.lblPersonagem_2.setObjectName(u"lblPersonagem_2")
        self.lblPersonagem_2.setGeometry(QRect(10, 0, 111, 41))
        font2 = QFont()
        font2.setFamilies([u"Microsoft YaHei"])
        font2.setPointSize(16)
        self.lblPersonagem_2.setFont(font2)
        self.lblPersonagem_2.setAutoFillBackground(False)
        self.lblPersonagem_2.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.lblPersonagem_2.setFrameShape(QFrame.Shape.NoFrame)
        self.lblPersonagem_2.setScaledContents(False)
        self.lblPersonagem_2.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.lblPersonagem_2.setWordWrap(False)
        self.btnCalcular = QPushButton(self.frmConfig)
        self.btnCalcular.setObjectName(u"btnCalcular")
        self.btnCalcular.setGeometry(QRect(160, 190, 151, 51))
        self.btnCalcular.setFont(font2)
        self.btnCalcular.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.btnCalcular.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.495, cy:0.153727, radius:1.53642, fx:0.495, fy:0.154, stop:0 rgba(168, 40, 56, 255), stop:0.789474 rgba(95, 18, 28, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    border-top: 1px solid rgb(148, 58, 77);     /* Bordas superior e esquerda mais claras (Luz) */\n"
"    border-left: 1px solid rgb(148, 58, 77);\n"
"    border-bottom: 1px solid rgb(78, 41, 40);  /* Bordas inferior e direita mais escuras (Sombra) */\n"
"    border-right: 1px solid rgb(148, 58, 77);    /* Borda sutil levemente mais clara que o fundo */\n"
"    border-radius: 4px;           /* Arredondamento dos cantos */\n"
"    padding: 3px 6px;\n"
"	margin: 1px;\n"
"")
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 270, 471, 271))
        palette6 = QPalette()
        gradient18 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient18.setSpread(QGradient.Spread.PadSpread)
        gradient18.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient18.setColorAt(0, QColor(94, 48, 48, 255))
        gradient18.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush25 = QBrush(gradient18)
        palette6.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush25)
        gradient19 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient19.setSpread(QGradient.Spread.PadSpread)
        gradient19.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient19.setColorAt(0, QColor(94, 48, 48, 255))
        gradient19.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush26 = QBrush(gradient19)
        palette6.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush26)
        gradient20 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient20.setSpread(QGradient.Spread.PadSpread)
        gradient20.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient20.setColorAt(0, QColor(94, 48, 48, 255))
        gradient20.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush27 = QBrush(gradient20)
        palette6.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush27)
        gradient21 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient21.setSpread(QGradient.Spread.PadSpread)
        gradient21.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient21.setColorAt(0, QColor(94, 48, 48, 255))
        gradient21.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush28 = QBrush(gradient21)
        palette6.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush28)
        gradient22 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient22.setSpread(QGradient.Spread.PadSpread)
        gradient22.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient22.setColorAt(0, QColor(94, 48, 48, 255))
        gradient22.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush29 = QBrush(gradient22)
        palette6.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush29)
        gradient23 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient23.setSpread(QGradient.Spread.PadSpread)
        gradient23.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient23.setColorAt(0, QColor(94, 48, 48, 255))
        gradient23.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush30 = QBrush(gradient23)
        palette6.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush30)
        gradient24 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient24.setSpread(QGradient.Spread.PadSpread)
        gradient24.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient24.setColorAt(0, QColor(94, 48, 48, 255))
        gradient24.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush31 = QBrush(gradient24)
        palette6.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush31)
        gradient25 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient25.setSpread(QGradient.Spread.PadSpread)
        gradient25.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient25.setColorAt(0, QColor(94, 48, 48, 255))
        gradient25.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush32 = QBrush(gradient25)
        palette6.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush32)
        gradient26 = QRadialGradient(0.495, 0.153727, 1.53642, 0.495, 0.154)
        gradient26.setSpread(QGradient.Spread.PadSpread)
        gradient26.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient26.setColorAt(0, QColor(94, 48, 48, 255))
        gradient26.setColorAt(0.789474, QColor(37, 22, 21, 255))
        brush33 = QBrush(gradient26)
        palette6.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush33)
        self.frame_2.setPalette(palette6)
        self.frame_2.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.495, cy:0.153727, radius:1.53642, fx:0.495, fy:0.154, stop:0 rgba(94, 48, 48, 255), stop:0.789474 rgba(37, 22, 21, 255));")
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.frame_2.setLineWidth(0)
        self.frmInfoTitulo_2 = QFrame(self.frame_2)
        self.frmInfoTitulo_2.setObjectName(u"frmInfoTitulo_2")
        self.frmInfoTitulo_2.setGeometry(QRect(0, 0, 521, 41))
        palette7 = QPalette()
        gradient27 = QLinearGradient(0, 0, 0.5, 0)
        gradient27.setSpread(QGradient.Spread.PadSpread)
        gradient27.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient27.setColorAt(0, QColor(148, 58, 77, 255))
        gradient27.setColorAt(1, QColor(116, 25, 38, 255))
        brush34 = QBrush(gradient27)
        palette7.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush34)
        gradient28 = QLinearGradient(0, 0, 0.5, 0)
        gradient28.setSpread(QGradient.Spread.PadSpread)
        gradient28.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient28.setColorAt(0, QColor(148, 58, 77, 255))
        gradient28.setColorAt(1, QColor(116, 25, 38, 255))
        brush35 = QBrush(gradient28)
        palette7.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush35)
        gradient29 = QLinearGradient(0, 0, 0.5, 0)
        gradient29.setSpread(QGradient.Spread.PadSpread)
        gradient29.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient29.setColorAt(0, QColor(148, 58, 77, 255))
        gradient29.setColorAt(1, QColor(116, 25, 38, 255))
        brush36 = QBrush(gradient29)
        palette7.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush36)
        gradient30 = QLinearGradient(0, 0, 0.5, 0)
        gradient30.setSpread(QGradient.Spread.PadSpread)
        gradient30.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient30.setColorAt(0, QColor(148, 58, 77, 255))
        gradient30.setColorAt(1, QColor(116, 25, 38, 255))
        brush37 = QBrush(gradient30)
        palette7.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush37)
        gradient31 = QLinearGradient(0, 0, 0.5, 0)
        gradient31.setSpread(QGradient.Spread.PadSpread)
        gradient31.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient31.setColorAt(0, QColor(148, 58, 77, 255))
        gradient31.setColorAt(1, QColor(116, 25, 38, 255))
        brush38 = QBrush(gradient31)
        palette7.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush38)
        gradient32 = QLinearGradient(0, 0, 0.5, 0)
        gradient32.setSpread(QGradient.Spread.PadSpread)
        gradient32.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient32.setColorAt(0, QColor(148, 58, 77, 255))
        gradient32.setColorAt(1, QColor(116, 25, 38, 255))
        brush39 = QBrush(gradient32)
        palette7.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush39)
        gradient33 = QLinearGradient(0, 0, 0.5, 0)
        gradient33.setSpread(QGradient.Spread.PadSpread)
        gradient33.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient33.setColorAt(0, QColor(148, 58, 77, 255))
        gradient33.setColorAt(1, QColor(116, 25, 38, 255))
        brush40 = QBrush(gradient33)
        palette7.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush40)
        gradient34 = QLinearGradient(0, 0, 0.5, 0)
        gradient34.setSpread(QGradient.Spread.PadSpread)
        gradient34.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient34.setColorAt(0, QColor(148, 58, 77, 255))
        gradient34.setColorAt(1, QColor(116, 25, 38, 255))
        brush41 = QBrush(gradient34)
        palette7.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush41)
        gradient35 = QLinearGradient(0, 0, 0.5, 0)
        gradient35.setSpread(QGradient.Spread.PadSpread)
        gradient35.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient35.setColorAt(0, QColor(148, 58, 77, 255))
        gradient35.setColorAt(1, QColor(116, 25, 38, 255))
        brush42 = QBrush(gradient35)
        palette7.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush42)
        self.frmInfoTitulo_2.setPalette(palette7)
        self.frmInfoTitulo_2.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.5, y2:0, stop:0 rgb(148, 58, 77), stop:1 rgb(116, 25, 38));")
        self.frmInfoTitulo_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frmInfoTitulo_2.setFrameShadow(QFrame.Shadow.Plain)
        self.lblPersonagem_3 = QLabel(self.frmInfoTitulo_2)
        self.lblPersonagem_3.setObjectName(u"lblPersonagem_3")
        self.lblPersonagem_3.setGeometry(QRect(10, 0, 151, 41))
        self.lblPersonagem_3.setFont(font2)
        self.lblPersonagem_3.setAutoFillBackground(False)
        self.lblPersonagem_3.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.lblPersonagem_3.setFrameShape(QFrame.Shape.NoFrame)
        self.lblPersonagem_3.setScaledContents(False)
        self.lblPersonagem_3.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.lblPersonagem_3.setWordWrap(False)
        self.lblClasse_2 = QLabel(self.frame_2)
        self.lblClasse_2.setObjectName(u"lblClasse_2")
        self.lblClasse_2.setGeometry(QRect(10, 50, 71, 31))
        palette8 = QPalette()
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush11)
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush)
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush11)
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush11)
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush12)
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush12)
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush13)
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush11)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush11)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush11)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush12)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush12)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush13)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush11)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush12)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush11)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush11)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush12)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush12)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush13)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        self.lblClasse_2.setPalette(palette8)
        self.lblClasse_2.setFont(font)
        self.lblClasse_2.setAutoFillBackground(False)
        self.lblClasse_2.setStyleSheet(u"background-color: rgb(58, 7, 21);    /* Tom vinho escuro do fundo da caixinha */\n"
"    color: rgb(190, 141, 142);\n"
"    border: 1px solid #4a1a24;    /* Borda sutil levemente mais clara que o fundo */\n"
"    border-radius: 4px;           /* Arredondamento dos cantos */\n"
"    padding: 3px 6px;\n"
"	margin: 1px;")
        self.lblClasse_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.lblClasse_2.setScaledContents(False)
        self.lblClasse_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblClasse_2.setWordWrap(False)
        self.lblClasse_3 = QLabel(self.frame_2)
        self.lblClasse_3.setObjectName(u"lblClasse_3")
        self.lblClasse_3.setGeometry(QRect(10, 80, 71, 31))
        palette9 = QPalette()
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush11)
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush)
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush11)
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush11)
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush12)
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush12)
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush13)
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush11)
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush)
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush11)
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush11)
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush12)
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush12)
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush13)
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush11)
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush12)
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush)
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush11)
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush11)
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush12)
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush12)
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush13)
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        self.lblClasse_3.setPalette(palette9)
        self.lblClasse_3.setFont(font)
        self.lblClasse_3.setAutoFillBackground(False)
        self.lblClasse_3.setStyleSheet(u"background-color: rgb(58, 7, 21);    /* Tom vinho escuro do fundo da caixinha */\n"
"    color: rgb(190, 141, 142);\n"
"    border: 1px solid #4a1a24;    /* Borda sutil levemente mais clara que o fundo */\n"
"    border-radius: 4px;           /* Arredondamento dos cantos */\n"
"    padding: 3px 6px;\n"
"	margin: 1px;")
        self.lblClasse_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.lblClasse_3.setFrameShadow(QFrame.Shadow.Plain)
        self.lblClasse_3.setScaledContents(False)
        self.lblClasse_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblClasse_3.setWordWrap(False)
        self.lblClasse_3.setMargin(0)
        self.lblClasse_4 = QLabel(self.frame_2)
        self.lblClasse_4.setObjectName(u"lblClasse_4")
        self.lblClasse_4.setGeometry(QRect(10, 140, 71, 31))
        palette10 = QPalette()
        palette10.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush11)
        palette10.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette10.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush)
        palette10.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush11)
        palette10.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush11)
        palette10.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush12)
        palette10.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush12)
        palette10.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush13)
        palette10.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette10.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush11)
        palette10.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette10.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush)
        palette10.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush11)
        palette10.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush11)
        palette10.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush12)
        palette10.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush12)
        palette10.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush13)
        palette10.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette10.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush11)
        palette10.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush12)
        palette10.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush)
        palette10.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush11)
        palette10.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush11)
        palette10.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush12)
        palette10.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush12)
        palette10.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush13)
        palette10.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette10.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        self.lblClasse_4.setPalette(palette10)
        self.lblClasse_4.setFont(font)
        self.lblClasse_4.setAutoFillBackground(False)
        self.lblClasse_4.setStyleSheet(u"background-color: rgb(58, 7, 21);    /* Tom vinho escuro do fundo da caixinha */\n"
"    color: rgb(190, 141, 142);\n"
"    border: 1px solid #4a1a24;    /* Borda sutil levemente mais clara que o fundo */\n"
"    border-radius: 4px;           /* Arredondamento dos cantos */\n"
"    padding: 3px 6px;\n"
"	margin: 1px;")
        self.lblClasse_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.lblClasse_4.setFrameShadow(QFrame.Shadow.Plain)
        self.lblClasse_4.setScaledContents(False)
        self.lblClasse_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblClasse_4.setWordWrap(False)
        self.lblClasse_4.setMargin(0)
        self.lblClasse_5 = QLabel(self.frame_2)
        self.lblClasse_5.setObjectName(u"lblClasse_5")
        self.lblClasse_5.setGeometry(QRect(10, 110, 71, 31))
        palette11 = QPalette()
        palette11.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush11)
        palette11.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette11.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush)
        palette11.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush11)
        palette11.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush11)
        palette11.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush12)
        palette11.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush12)
        palette11.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush13)
        palette11.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette11.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush11)
        palette11.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette11.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush)
        palette11.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush11)
        palette11.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush11)
        palette11.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush12)
        palette11.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush12)
        palette11.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush13)
        palette11.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette11.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush11)
        palette11.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush12)
        palette11.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush)
        palette11.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush11)
        palette11.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush11)
        palette11.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush12)
        palette11.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush12)
        palette11.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush13)
        palette11.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette11.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        self.lblClasse_5.setPalette(palette11)
        self.lblClasse_5.setFont(font)
        self.lblClasse_5.setAutoFillBackground(False)
        self.lblClasse_5.setStyleSheet(u"background-color: rgb(58, 7, 21);    /* Tom vinho escuro do fundo da caixinha */\n"
"    color: rgb(190, 141, 142);\n"
"    border: 1px solid #4a1a24;    /* Borda sutil levemente mais clara que o fundo */\n"
"    border-radius: 4px;           /* Arredondamento dos cantos */\n"
"    padding: 3px 6px;\n"
"	margin: 1px;")
        self.lblClasse_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.lblClasse_5.setScaledContents(False)
        self.lblClasse_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblClasse_5.setWordWrap(False)
        self.lblClasse_6 = QLabel(self.frame_2)
        self.lblClasse_6.setObjectName(u"lblClasse_6")
        self.lblClasse_6.setGeometry(QRect(10, 200, 71, 31))
        palette12 = QPalette()
        palette12.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush11)
        palette12.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette12.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush)
        palette12.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush11)
        palette12.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush11)
        palette12.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush12)
        palette12.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush12)
        palette12.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush13)
        palette12.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette12.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush11)
        palette12.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette12.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush)
        palette12.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush11)
        palette12.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush11)
        palette12.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush12)
        palette12.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush12)
        palette12.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush13)
        palette12.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette12.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush11)
        palette12.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush12)
        palette12.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush)
        palette12.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush11)
        palette12.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush11)
        palette12.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush12)
        palette12.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush12)
        palette12.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush13)
        palette12.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        self.lblClasse_6.setPalette(palette12)
        self.lblClasse_6.setFont(font)
        self.lblClasse_6.setAutoFillBackground(False)
        self.lblClasse_6.setStyleSheet(u"background-color: rgb(58, 7, 21);    /* Tom vinho escuro do fundo da caixinha */\n"
"    color: rgb(190, 141, 142);\n"
"    border: 1px solid #4a1a24;    /* Borda sutil levemente mais clara que o fundo */\n"
"    border-radius: 4px;           /* Arredondamento dos cantos */\n"
"    padding: 3px 6px;\n"
"	margin: 1px;")
        self.lblClasse_6.setFrameShape(QFrame.Shape.StyledPanel)
        self.lblClasse_6.setScaledContents(False)
        self.lblClasse_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblClasse_6.setWordWrap(False)
        self.lblClasse_7 = QLabel(self.frame_2)
        self.lblClasse_7.setObjectName(u"lblClasse_7")
        self.lblClasse_7.setGeometry(QRect(10, 230, 71, 31))
        palette13 = QPalette()
        palette13.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush11)
        palette13.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette13.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush)
        palette13.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush11)
        palette13.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush11)
        palette13.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush12)
        palette13.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush12)
        palette13.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush13)
        palette13.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette13.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush11)
        palette13.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette13.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush)
        palette13.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush11)
        palette13.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush11)
        palette13.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush12)
        palette13.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush12)
        palette13.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush13)
        palette13.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette13.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush11)
        palette13.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush12)
        palette13.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush)
        palette13.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush11)
        palette13.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush11)
        palette13.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush12)
        palette13.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush12)
        palette13.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush13)
        palette13.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        self.lblClasse_7.setPalette(palette13)
        self.lblClasse_7.setFont(font)
        self.lblClasse_7.setAutoFillBackground(False)
        self.lblClasse_7.setStyleSheet(u"background-color: rgb(58, 7, 21);    /* Tom vinho escuro do fundo da caixinha */\n"
"    color: rgb(190, 141, 142);\n"
"    border: 1px solid #4a1a24;    /* Borda sutil levemente mais clara que o fundo */\n"
"    border-radius: 4px;           /* Arredondamento dos cantos */\n"
"    padding: 3px 6px;\n"
"	margin: 1px;")
        self.lblClasse_7.setFrameShape(QFrame.Shape.StyledPanel)
        self.lblClasse_7.setFrameShadow(QFrame.Shadow.Plain)
        self.lblClasse_7.setScaledContents(False)
        self.lblClasse_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblClasse_7.setWordWrap(False)
        self.lblClasse_7.setMargin(0)
        self.lblClasse_8 = QLabel(self.frame_2)
        self.lblClasse_8.setObjectName(u"lblClasse_8")
        self.lblClasse_8.setGeometry(QRect(10, 170, 71, 31))
        palette14 = QPalette()
        palette14.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush11)
        palette14.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette14.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush)
        palette14.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush11)
        palette14.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush11)
        palette14.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush12)
        palette14.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush12)
        palette14.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush13)
        palette14.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette14.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush11)
        palette14.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette14.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush)
        palette14.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush11)
        palette14.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush11)
        palette14.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush12)
        palette14.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush12)
        palette14.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush13)
        palette14.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        palette14.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush11)
        palette14.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush12)
        palette14.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush)
        palette14.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush11)
        palette14.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush11)
        palette14.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush12)
        palette14.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush12)
        palette14.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush13)
        palette14.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush14)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush15)
#endif
        self.lblClasse_8.setPalette(palette14)
        self.lblClasse_8.setFont(font)
        self.lblClasse_8.setAutoFillBackground(False)
        self.lblClasse_8.setStyleSheet(u"background-color: rgb(58, 7, 21);    /* Tom vinho escuro do fundo da caixinha */\n"
"    color: rgb(190, 141, 142);\n"
"    border: 1px solid #4a1a24;    /* Borda sutil levemente mais clara que o fundo */\n"
"    border-radius: 4px;           /* Arredondamento dos cantos */\n"
"    padding: 3px 6px;\n"
"	margin: 1px;")
        self.lblClasse_8.setFrameShape(QFrame.Shape.StyledPanel)
        self.lblClasse_8.setFrameShadow(QFrame.Shadow.Plain)
        self.lblClasse_8.setScaledContents(False)
        self.lblClasse_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lblClasse_8.setWordWrap(False)
        self.lblClasse_8.setMargin(0)
        self.lblHpInt = QLabel(self.frame_2)
        self.lblHpInt.setObjectName(u"lblHpInt")
        self.lblHpInt.setGeometry(QRect(90, 50, 80, 31))
        self.lblHpInt.setFont(font2)
        self.lblHpInt.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.lblAtkInt = QLabel(self.frame_2)
        self.lblAtkInt.setObjectName(u"lblAtkInt")
        self.lblAtkInt.setGeometry(QRect(90, 80, 80, 31))
        self.lblAtkInt.setFont(font2)
        self.lblAtkInt.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.lblSpdInt = QLabel(self.frame_2)
        self.lblSpdInt.setObjectName(u"lblSpdInt")
        self.lblSpdInt.setGeometry(QRect(90, 140, 80, 31))
        self.lblSpdInt.setFont(font2)
        self.lblSpdInt.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.lblSklInt = QLabel(self.frame_2)
        self.lblSklInt.setObjectName(u"lblSklInt")
        self.lblSklInt.setGeometry(QRect(90, 110, 80, 31))
        self.lblSklInt.setFont(font2)
        self.lblSklInt.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.lblResInt = QLabel(self.frame_2)
        self.lblResInt.setObjectName(u"lblResInt")
        self.lblResInt.setGeometry(QRect(90, 230, 80, 31))
        self.lblResInt.setFont(font2)
        self.lblResInt.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.lblDefInt = QLabel(self.frame_2)
        self.lblDefInt.setObjectName(u"lblDefInt")
        self.lblDefInt.setGeometry(QRect(90, 200, 80, 31))
        self.lblDefInt.setFont(font2)
        self.lblDefInt.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.lblLckInt = QLabel(self.frame_2)
        self.lblLckInt.setObjectName(u"lblLckInt")
        self.lblLckInt.setGeometry(QRect(90, 170, 80, 31))
        self.lblLckInt.setFont(font2)
        self.lblLckInt.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.frame = QFrame(self.frame_2)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(5, 45, 151, 221))
        self.frame.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.frame.setStyleSheet(u"background-color: rgba(0, 0, 0, 80);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QFrame.Shadow.Plain)
        self.frame.setLineWidth(0)
        self.widget = QWidget(self.frame_2)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(80, 40, 341, 341))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet(u"border-image: url(:/portraits/Alm.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.widget.raise_()
        self.frame.raise_()
        self.frmInfoTitulo_2.raise_()
        self.lblClasse_2.raise_()
        self.lblClasse_3.raise_()
        self.lblClasse_4.raise_()
        self.lblClasse_5.raise_()
        self.lblClasse_6.raise_()
        self.lblClasse_7.raise_()
        self.lblClasse_8.raise_()
        self.lblHpInt.raise_()
        self.lblAtkInt.raise_()
        self.lblSpdInt.raise_()
        self.lblSklInt.raise_()
        self.lblResInt.raise_()
        self.lblDefInt.raise_()
        self.lblLckInt.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 491, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.lblPersonagem.setText(QCoreApplication.translate("MainWindow", u"Unit Name", None))
        self.lblClasse.setText(QCoreApplication.translate("MainWindow", u"Class", None))
        self.lblNivel.setText(QCoreApplication.translate("MainWindow", u"Level", None))
        self.lblPersonagem_2.setText(QCoreApplication.translate("MainWindow", u"Unit Info", None))
        self.btnCalcular.setText(QCoreApplication.translate("MainWindow", u"CALCULATE", None))
        self.lblPersonagem_3.setText(QCoreApplication.translate("MainWindow", u"Average Stats", None))
        self.lblClasse_2.setText(QCoreApplication.translate("MainWindow", u"HP", None))
        self.lblClasse_3.setText(QCoreApplication.translate("MainWindow", u"ATK", None))
        self.lblClasse_4.setText(QCoreApplication.translate("MainWindow", u"SPD", None))
        self.lblClasse_5.setText(QCoreApplication.translate("MainWindow", u"SKILL", None))
        self.lblClasse_6.setText(QCoreApplication.translate("MainWindow", u"DEF", None))
        self.lblClasse_7.setText(QCoreApplication.translate("MainWindow", u"RES", None))
        self.lblClasse_8.setText(QCoreApplication.translate("MainWindow", u"LCK", None))
        self.lblHpInt.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lblAtkInt.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lblSpdInt.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lblSklInt.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lblResInt.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lblDefInt.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.lblLckInt.setText(QCoreApplication.translate("MainWindow", u"-", None))
    # retranslateUi

